### ISSUE TITLE
快捷机器合成单个原版物品报错

### ISSUE THREAD

**Issue by voila1106** [ecro-fun/FinalTECH#5]
## Description (Required)

快捷机器合成单个原版物品报错

## Steps to reproduce the Issue (Required)

比如快捷冶炼炉
放入 1 个铁粉，生成物是 1 个铁锭
点击合成，铁粉消失，没有合成铁锭，“点击合成” 玻璃板被取下

## Expected behavior (Required)

正常合成单个原版物品

## Server Log / Error Report

```
[04:16:07 ERROR]: Could not pass event InventoryClickEvent to Slimefun v2022.06-release
java.lang.UnsupportedOperationException: This ItemStack has no ItemMeta! Make sure to check ItemStack#hasItemMeta() before accessing this method!
        at io.github.thebusybiscuit.slimefun4.utils.itemstack.ItemStackWrapper.getItemMeta(ItemStackWrapper.java:61) ~[Slimefun-v2022.06-release.jar:?]
        at org.bukkit.inventory.ItemStack.getDurability(ItemStack.java:234) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:34) ~[paper-1.19.jar:git-Paper-52]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[paper-1.19.jar:git-Paper-52]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.replaceExistingItem(ChestMenu.java:243) ~[Slimefun-v2022.06-release.jar:?]
        at me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.replaceExistingItem(DirtyChestMenu.java:169) ~[Slimefun-v2022.06-release.jar:?]
        at me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.replaceExistingItem(DirtyChestMenu.java:160) ~[Slimefun-v2022.06-release.jar:?]
        at me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.pushItem(DirtyChestMenu.java:120) ~[Slimefun-v2022.06-release.jar:?]
        at io.taraxacum.finaltech.core.menu.manual.ManualCraftMachineMenu.lambda$newInstance$5(ManualCraftMachineMenu.java:140) ~[FinalTech.jar:?]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:54) ~[Slimefun-v2022.06-release.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3047) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-52]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
## Environment (Required)

![image](https://user-images.githubusercontent.com/40945986/179304283-c542789a-82c0-40da-858e-4a044326572a.png)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by ecro-fun** [comment]
OK. It will be fixed soon.
