### ISSUE TITLE
Plug-in failed to start

### ISSUE THREAD

**Issue by ddos-ling** [ecro-fun/FinalTECH#8]
## Description (Required)
Plug-in failed to start

## Steps to reproduce the Issue (Required)
Start Server

## Server Log / Error Report
```
[20:26:59 INFO]: [FinalTECH] Enabling FinalTECH vBuild 68 zh-CN(ECRO) (git 24b97ec)
[20:26:59 INFO]: [FinalTECH] You have enabled the config updater.
[20:26:59 INFO]: [FinalTECH] You have enabled the config updater for language file
[20:26:59 INFO]: [FinalTECH] You are using the latest version. Good luck!
[20:26:59 ERROR]: Error occurred while enabling FinalTECH vBuild 68 zh-CN(ECRO) (git 24b97ec) (Is it up to date?)
java.lang.IllegalArgumentException: Cannot set already-set enchantment
        at org.bukkit.enchantments.Enchantment.registerEnchantment(Enchantment.java:386) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at io.taraxacum.finaltech.setup.SetupUtil.init(SetupUtil.java:114) ~[74-FinalTECH-Build 68 zh-CN(ECRO) (git 24b97ec).jar:?]
        at io.taraxacum.finaltech.FinalTech.onEnable(FinalTech.java:178) ~[74-FinalTECH-Build 68 zh-CN(ECRO) (git 24b97ec).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:26:59 INFO]: [FinalTECH] Disabling FinalTECH vBuild 68 zh-CN(ECRO) (git 24b97ec)
[20:26:59 INFO]: [FinalTECH] Waiting all task to end.(0)
```

## Environment (Required)
```
> sf versions
[20:51:11 INFO]: Slimefun 运行的服务器环境:
[20:51:11 INFO]: Purpur git-Purpur-1858 (MC: 1.19.2)
[20:51:11 INFO]: Slimefun 2022.12-release
[20:51:11 INFO]: Metrics-组件 #28
[20:51:11 INFO]: Java 17
[20:51:11 INFO]: 
[20:51:11 INFO]: 由 StarWishsama 汉化
[20:51:11 INFO]: 请不要将此版本信息截图到 Discord/Github 反馈 Bug
[20:51:11 INFO]: 优先到汉化页面反馈
[20:51:11 INFO]: 
[20:51:11 INFO]: 安装的附属插件: (15)
[20:51:11 INFO]:   GuizhanLibPlugin vBuild 18 (git 88ff423)
[20:51:11 INFO]:   Bump vBuild 30 zh-CN(SlimefunGuguProject) (git 31e1bb3)
[20:51:11 INFO]:   Residence v5.1.0.1
[20:51:11 INFO]:   ExtraGear vBuild 2 zh-CN(ybw0014) (git ff13031)
[20:51:11 INFO]:   ExoticGarden vBuild 11 zh-CN(ybw0014) (git 2b05290)
[20:51:11 INFO]:   CMILib v1.2.4.1
[20:51:11 INFO]:   FinalTECH vBuild 68 zh-CN(ECRO) (git 24b97ec)
[20:51:11 INFO]:   InfinityExpansion vBuild 5 zh-CN(SlimefunGuguProject) (git 018bfe1)
[20:51:11 INFO]:   LiteXpansion vBuild 22 zh-CN(ybw0014) (git 8e27b7f)
[20:51:11 INFO]:   IllegalStack v2.6.1
[20:51:11 INFO]:   ExtraHeads vBuild 6 zh-CN(ybw0014) (git 03b51c1)
[20:51:11 INFO]:   SlimyTreeTaps vBuild 2 zh-CN(ybw0014) (git 8a58b9f)
[20:51:11 INFO]:   SlimeTinker vBuild 42 zh-CN(ybw0014) (git 4be3be4)
[20:51:11 INFO]:   SimpleStorage vBuild 5 zh-CN(ybw0014) (git c443c7b)
[20:51:11 INFO]:   FluffyMachines vBuild 15 zh-CN(baoad) (git a024fb3)
```

 - Minecraft Version: Current: git-Purpur-1858 (MC: 1.19.2)*  Previous: git-Paper-307 (MC: 1.19.2)
 - CS-CoreLib Version: Not installed
 - Slimefun Version: 2022.12-release
 - Plugin Version: Build 68 zh-CN(ECRO) (git 24b97ec)

**Comment by ecro-fun** [comment]
Have you installed any enchantment plugin?
It seems that two enchantment with name " " is being registered.

**Comment by ddos-ling** [comment]
My server does not have plugin for enchantment.

**Comment by ecro-fun** [comment]
It may be fixed in the next version.

**Comment by ecro-fun** [comment]
It should be fixed now
